# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: broswen@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 80:80
