version: '3.1'

services:
  taskla:
    build: .
    image: taskla
    # sleep for 4 seconds before starting, wait for postgres to finish starting
    command: sh -c "
      sleep 4 &&
      ./taskla"
    environment: 
      - SECRET_KEY=supersecretkey
      - DB_HOST=postgres
      - DB_NAME=taskla
      - DB_USER=taskla
      - DB_PASSWORD=password
      - DB_PORT=5432
    depends_on: 
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: taskla
      POSTGRES_DB: taskla
    # ports:
    #   - 5432:5432

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment: 
  #     PGADMIN_DEFAULT_EMAIL: user@test.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - 80:80
  #   depends_on: 
  #     - postgres
